name: '${project.name}'
version: '${project.version}'
author: Fonkio
main: fr.fonkio.chunkentities.ChunkEntities
commands:
  entities:
    description: Displays a map of chunks with the number of entities
    permission: chunkentites.entite
