name: ChunkEntities
version: 1.0
author: Fonkio
main: fr.fonkio.chunkentities.ChunkEntities
commands:
  entite:
    description: Commande pour la carte des entites
    permission: chunkentites.entite
